openapi: 3.0.0
info:
  title: Carbon Trading API
  version: 1.0.0
servers:
  - url: https://carbon-rights-backend-334c8980a6b5.herokuapp.com/api
paths:
  /auth/register:
    post:
      summary: Register a new user
      tags:
        - Authentication
  /auth/verify-otp:
    post:
      summary: Send OTP for verification
      tags:
        - Authentication
  /auth/verify-otp-code:
    post:
      summary: Verify OTP code
      tags:
        - Authentication
  /auth/login:
    post:
      summary: User login
      tags:
        - Authentication
  /auth/social-login/{provider}:
    post:
      summary: Social login
      parameters:
        - name: provider
          in: path
          required: true
          schema:
            type: string
      tags:
        - Authentication
  /auth/forgot-password:
    post:
      summary: Request password reset
      tags:
        - Authentication
  /auth/change-password:
    post:
      summary: Change user password
      security:
        - BearerAuth: []
      tags:
        - Authentication

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
